[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "sphinx_autobuild"
dist-name = "sphinx-autobuild"
description-file = "README.rst"
author = "Jonathan Stoppani"
author-email = "jonathan@stoppani.name"
classifiers = [
  "Development Status :: 4 - Beta",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
  "Programming Language :: Python",
  "Programming Language :: Python :: 2",
  "Programming Language :: Python :: 2.7",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.4",
  "Programming Language :: Python :: 3.5",
  "Programming Language :: Python :: 3.6",
  "Topic :: Software Development :: Libraries :: Python Modules",
]
home-page = "https://github.com/GaretJax/sphinx_autobuild"
license = "MIT"
requires = [
  "sphinx",
  "watchdog",
  "livereload",
]

[tool.flit.scripts]
sphinx-autobuild = "sphinx_autobuild.__main__:main"

[tool.flit.metadata.requires-extra]
test = ["mock", "pytest", "pytest-cov"]
docs = []
